# Generated by Django 6.0.3 on 2026-05-28 07:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0002_tenant_balance_alter_tenant_billing_external_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0, help_text='Amount charged from the balance each period.', max_digits=14)),
                ('period_days', models.PositiveIntegerField(default=30, help_text='Length of one billing period, in days.')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('CANCELED', 'Canceled')], db_index=True, default='ACTIVE', max_length=12)),
                ('paid_through', models.DateTimeField(blank=True, null=True)),
                ('warn_days', models.PositiveIntegerField(default=3, help_text='Days before cut-off to start warning the POS.')),
                ('last_charged_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('kind', models.CharField(choices=[('TOPUP', 'Top-up (money in)'), ('CHARGE', 'Subscription charge (money out)'), ('ADJUST', 'Manual adjustment')], db_index=True, max_length=8)),
                ('source', models.CharField(choices=[('MANUAL', 'Manual (admin)'), ('CLICK', 'Click.uz'), ('PAYME', 'Payme.uz'), ('SYSTEM', 'System (subscription charge)')], db_index=True, default='MANUAL', max_length=8)),
                ('external_id', models.CharField(blank=True, default='', max_length=128)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=14)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', '-created_at'], name='billing_pay_tenant__c18eb6_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('external_id', ''), _negated=True), fields=('source', 'external_id'), name='payment_unique_source_external_id')],
            },
        ),
    ]
