# Generated by Django 6.0.3 on 2026-05-30 10:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_subscription_grace_and_warning_tracking'),
        ('tenants', '0002_tenant_balance_alter_tenant_billing_external_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(help_text='Short stable identifier (e.g. "basic", "pro").', max_length=32, unique=True)),
                ('name', models.CharField(help_text='Display name shown to the customer in the setup wizard.', max_length=120)),
                ('description', models.TextField(blank=True, default='', help_text='One- or two-line pitch shown next to the price.')),
                ('price', models.DecimalField(decimal_places=2, help_text="So'm charged each period from the prepaid wallet.", max_digits=14)),
                ('period_days', models.PositiveIntegerField(default=30, help_text='Length of one billing period, in days.')),
                ('warn_days', models.PositiveIntegerField(default=3, help_text='Days before cut-off to start warning the POS.')),
                ('grace_days', models.PositiveIntegerField(default=3, help_text='Days of soft cushion after paid_through before lockout.')),
                ('is_active', models.BooleanField(default=True, help_text='Hide retired plans from the wizard without deleting them.')),
                ('sort_order', models.PositiveIntegerField(default=100, help_text='Display order — lower first.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'price'],
            },
        ),
        migrations.AddField(
            model_name='subscription',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='billing.subscriptionplan'),
        ),
        migrations.CreateModel(
            name='PlanChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending vendor approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=12)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.CharField(blank=True, default='', max_length=255)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan_change_decisions', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_change_requests', to='tenants.tenant')),
                ('current_plan', models.ForeignKey(blank=True, help_text='Snapshot of the plan the tenant was on when the request was filed.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='billing.subscriptionplan')),
                ('requested_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='billing.subscriptionplan')),
            ],
            options={
                'ordering': ['-requested_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'PENDING')), fields=('tenant',), name='one_pending_plan_change_per_tenant')],
            },
        ),
    ]
