# Generated by Django 6.0.3 on 2026-08-13 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_subscriptionplan_subscription_plan_planchangerequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('charged_count', models.PositiveIntegerField(default=0)),
                ('warning_count', models.PositiveIntegerField(default=0)),
                ('grace_count', models.PositiveIntegerField(default=0)),
                ('lockout_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-completed_at'],
            },
        ),
    ]
