# Generated by Django 6.0.7 on 2026-08-14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0006_billingrun"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payments",
                to="tenants.tenant",
            ),
        ),
    ]
