# Generated by Django 6.0.3 on 2026-05-23 18:22

import django.db.models.deletion
import tenants.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('billing_external_id', models.CharField(blank=True, default='', help_text='Stripe customer ID (or similar). Empty in v1.', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['org_name'],
            },
        ),
        migrations.CreateModel(
            name='InviteCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, default=tenants.models._new_invite_code, max_length=32, unique=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='If set, registrations with this code after this time are refused.', null=True)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('intended_email', models.EmailField(blank=True, default='', max_length=254)),
                ('intended_org_name', models.CharField(blank=True, default='', max_length=200)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invite_codes', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
