# Generated by Django 6.0.3 on 2026-05-28 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Prepaid balance. Charged per subscription period.', max_digits=14),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='billing_external_id',
            field=models.CharField(blank=True, default='', help_text='Payment provider customer ID (or similar). Optional.', max_length=64),
        ),
    ]
