# Generated by Django 6.0.3 on 2026-08-13 20:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, db_index=True, max_length=150)),
                ('ip', models.GenericIPAddressField(blank=True, db_index=True, null=True)),
                ('success', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VendorSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('refresh_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('access_expires_at', models.DateTimeField(db_index=True)),
                ('refresh_expires_at', models.DateTimeField(db_index=True)),
                ('revoked_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_refreshed_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('tenants_write', 'Can create and edit tenants'), ('licenses_control', 'Can control licenses'), ('billing_approve', 'Can approve billing plan changes'), ('invites_manage', 'Can create and revoke invites'), ('plans_manage', 'Can maintain subscription plans'), ('subscriptions_write', 'Can edit subscription policy fields'), ('view_sensitive_heartbeat', 'Can view raw heartbeat payloads')],
            },
        ),
        migrations.CreateModel(
            name='IdempotencyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('method', models.CharField(max_length=8)),
                ('path', models.CharField(max_length=500)),
                ('request_hash', models.CharField(max_length=64)),
                ('response_status', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('response_body', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'key'), name='vendor_idempotency_user_key')],
            },
        ),
    ]
