# Generated by Django 6.0.3 on 2026-05-23 18:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('SUSPEND', 'Suspend'), ('RESUME', 'Resume'), ('REVOKE', 'Revoke'), ('EXTEND_EXPIRY', 'Extend expiry'), ('SET_MESSAGE', 'Set banner message'), ('INVITE_CREATE', 'Invite code created'), ('INVITE_REVOKE', 'Invite code revoked'), ('UNLOCK_GENERATED', 'Perpetual unlock generated')], db_index=True, max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='control_events', to=settings.AUTH_USER_MODEL)),
                ('license_key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='control_events', to='licenses.licensekey')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='control_events', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HeartbeatEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ack_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('received_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('client_version', models.CharField(blank=True, default='', max_length=120)),
                ('branch_id', models.CharField(blank=True, default='', max_length=120)),
                ('fingerprint', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('license_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heartbeat_events', to='licenses.licensekey')),
            ],
            options={
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['license_key', '-received_at'], name='licenses_he_license_d2144b_idx')],
            },
        ),
    ]
