# Generated by Django 6.0.3 on 2026-08-13 20:07

from django.db import migrations, models
from django.utils import timezone


def backfill_revoked_at(apps, _schema_editor):
    LicenseKey = apps.get_model('licenses', 'LicenseKey')
    LicenseKey.objects.filter(
        status='REVOKED', revoked_at__isnull=True,
    ).update(revoked_at=timezone.now())


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0002_controlevent_heartbeatevent'),
    ]

    operations = [
        migrations.RunPython(backfill_revoked_at, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='controlevent',
            name='action',
            field=models.CharField(choices=[('SUSPEND', 'Suspend'), ('RESUME', 'Resume'), ('REVOKE', 'Revoke'), ('EXTEND_EXPIRY', 'Extend expiry'), ('SET_MESSAGE', 'Set banner message'), ('INVITE_CREATE', 'Invite code created'), ('INVITE_REVOKE', 'Invite code revoked'), ('PLAN_CHANGE_APPROVE', 'Plan change approved'), ('PLAN_CHANGE_REJECT', 'Plan change rejected'), ('UNLOCK_GENERATED', 'Perpetual unlock generated')], db_index=True, max_length=32),
        ),
    ]
