from django.contrib import admin

from tenants.models import InviteCode, Tenant


@admin.register(Tenant)
class TenantAdmin(admin.ModelAdmin):
    """Read-only on the wallet: top-ups flow in only through the payment
    providers (Click.uz, Payme.uz). The control center has no manual
    "Add credit" form — keep money movement on a single, auditable rail."""
    list_display = ('org_name', 'email', 'balance', 'created_at')
    search_fields = ('org_name', 'email', 'notes')
    readonly_fields = ('balance', 'created_at', 'updated_at')
    ordering = ('org_name',)


@admin.register(InviteCode)
class InviteCodeAdmin(admin.ModelAdmin):
    list_display = (
        'code', 'intended_org_name', 'intended_email',
        'consumed_at', 'expires_at', 'tenant',
    )
    list_filter = ('consumed_at', 'expires_at')
    search_fields = ('code', 'intended_email', 'intended_org_name', 'notes')
    readonly_fields = ('code', 'consumed_at', 'tenant', 'created_at')

    # Issuing a new invite is the most common admin operation — keep the
    # form short. The code is auto-generated by the model default.
    fields = (
        'intended_org_name', 'intended_email', 'expires_at', 'notes',
        'code', 'consumed_at', 'tenant', 'created_at',
    )
